/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoomRouteImport } from './routes/room'
import { Route as MyProjectsRouteImport } from './routes/my-projects'
import { Route as AboutMeRouteImport } from './routes/about-me'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyProjectsProjectRouteImport } from './routes/my-projects_.$project'

const RoomRoute = RoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProjectsRoute = MyProjectsRouteImport.update({
  id: '/my-projects',
  path: '/my-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMeRoute = AboutMeRouteImport.update({
  id: '/about-me',
  path: '/about-me',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProjectsProjectRoute = MyProjectsProjectRouteImport.update({
  id: '/my-projects_/$project',
  path: '/my-projects/$project',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/my-projects': typeof MyProjectsRoute
  '/room': typeof RoomRoute
  '/my-projects/$project': typeof MyProjectsProjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/my-projects': typeof MyProjectsRoute
  '/room': typeof RoomRoute
  '/my-projects/$project': typeof MyProjectsProjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/my-projects': typeof MyProjectsRoute
  '/room': typeof RoomRoute
  '/my-projects_/$project': typeof MyProjectsProjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-me'
    | '/my-projects'
    | '/room'
    | '/my-projects/$project'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about-me' | '/my-projects' | '/room' | '/my-projects/$project'
  id:
    | '__root__'
    | '/'
    | '/about-me'
    | '/my-projects'
    | '/room'
    | '/my-projects_/$project'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutMeRoute: typeof AboutMeRoute
  MyProjectsRoute: typeof MyProjectsRoute
  RoomRoute: typeof RoomRoute
  MyProjectsProjectRoute: typeof MyProjectsProjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/room': {
      id: '/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-projects': {
      id: '/my-projects'
      path: '/my-projects'
      fullPath: '/my-projects'
      preLoaderRoute: typeof MyProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-me': {
      id: '/about-me'
      path: '/about-me'
      fullPath: '/about-me'
      preLoaderRoute: typeof AboutMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-projects_/$project': {
      id: '/my-projects_/$project'
      path: '/my-projects/$project'
      fullPath: '/my-projects/$project'
      preLoaderRoute: typeof MyProjectsProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutMeRoute: AboutMeRoute,
  MyProjectsRoute: MyProjectsRoute,
  RoomRoute: RoomRoute,
  MyProjectsProjectRoute: MyProjectsProjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
