name: Check for pull requests

on:
  # Triggers the workflow on pull request events targeting the default branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      deploy: false
